### ISSUE TITLE
Npm install failed

### ISSUE THREAD

**Issue by christopherdiehl** [mixmaxhq/giphy-example-slash-command#6]
`npm install` fails on my Mac running Node v7. I receive the following error:

```
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.15 install script 'node build.js || nodejs build.js'.
```

Any ideas on how to fix?

**Comment by bradvogel** [comment]
Try again. I just removed the package that was failing. https://github.com/mixmaxhq/giphy-example-slash-command/pull/7
